### ISSUE TITLE
Verification notice

### ISSUE THREAD

**Issue by CStelian** [RiverVanRain/verification#1]
Would be a great feature if we could change the verification notice, kinda the way Facebook and Twitter have when you press on the checkmark.

**Comment by RiverVanRain** [comment]
@HelloThere838 I will do. Thanks.

**Comment by RiverVanRain** [comment]
Fixed [2e777aa](https://github.com/RiverVanRain/verification/commit/2e777aadc3b8c6e3a1fc8e659fcf1f12fbc2e7df)
